all: 
	sudo /usr/local/go/bin/go build main.go led.go network.go

# main: led network
# 	sudo /usr/local/go/bin/go build main.go
# led:
# 	sudo /usr/local/go/bin/go build led.go
# network:
# 	sudo /usr/local/go/bin/go build network.go
